language: generic

before_install:
   - sudo apt update
   - sudo apt install -yq python-imaging python-usb
   - wget http://weewx.com/downloads/weewx_3.8.0-1_all.deb
   - sudo dpkg -i weewx_3.8.0-1_all.deb

script:
   - sudo ./setup_reports.sh
   - sudo ./test_wee_reports.sh
   - sudo ls /tmp/weewx/skins/oberlibtv
   - sudo ls /tmp/weewx/html
   - sudo cat /tmp/weewx/index.html
