language: generic

before_install:
   - sudo apt update
   - sudo apt install -yq python-imaging python-usb
   - wget http://weewx.com/downloads/weewx_3.8.0-1_all.deb
   - sudo dpkg -i weewx_3.8.0-1_all.deb
   - sudo date
   - sudo ntpdate ntp.ubuntu.com

script:
   - sudo ./setup_reports.sh
   - sudo ./test_wee_reports.sh
   - sudo cat /var/log/syslog | grep wee
   - sudo ls /tmp/weewx/skins/oberlintv
   - sudo ls /tmp/weewx/html
   - sudo cat /tmp/weewx/html/index.html
